version: '2'

services:
  portal:
    image: marc1060/minstra
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - /opt/stalker/stalker_portal:/var/www/stalker_portal
    depends_on:
      - db
  db:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=stalker_db
      - MYSQL_USER=stalker
      - MYSQL_PASSWORD=stalkerpass
    volumes:
      - /opt/stalker/mysql_data:/var/lib/mysql
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/conf/portainer:/data
    restart: always
